dist: bionic
language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic
  matrix:
    - laravel=^7.0
    - laravel=^8.0
    - setup=stable laravel=^7.0
    - setup=stable laravel=^8.0
    - setup=lowest laravel=^7.0
    - setup=lowest laravel=^8.0

dist: trusty

before_install:
  - if [[ $xdebug = 'true' ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - composer config discard-changes true

install:
  - travis_retry composer require "laravel/framework=${laravel}" --prefer-source --no-interaction --no-suggest
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - vendor/bin/phpunit -c ./ --verbose

matrix:
  fast_finish: true
